/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		VITE_NAVER_MAP_CLIENT_ID: string;
	}
}
interface Env extends Cloudflare.Env {}
