/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestDesignsRouteImport } from './routes/test-designs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WikiAllRouteImport } from './routes/wiki/all'
import { Route as WikiSlugRouteImport } from './routes/wiki/$slug'
import { Route as AdminWebSourcesRouteImport } from './routes/admin/web-sources'
import { Route as AdminToolsRouteImport } from './routes/admin/tools'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as WikiSlugIndexRouteImport } from './routes/wiki/$slug.index'
import { Route as EventHalfpriceTravelIndexRouteImport } from './routes/event/halfprice-travel/index'
import { Route as WikiSlugReviewsRouteImport } from './routes/wiki/$slug.reviews'
import { Route as WikiSlugMediaRouteImport } from './routes/wiki/$slug.media'
import { Route as WikiSlugBlogRouteImport } from './routes/wiki/$slug.blog'
import { Route as EventHalfpriceTravelSlugRouteImport } from './routes/event/halfprice-travel/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestDesignsRoute = TestDesignsRouteImport.update({
  id: '/test-designs',
  path: '/test-designs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WikiAllRoute = WikiAllRouteImport.update({
  id: '/wiki/all',
  path: '/wiki/all',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebSourcesRoute = AdminWebSourcesRouteImport.update({
  id: '/web-sources',
  path: '/web-sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const WikiSlugIndexRoute = WikiSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiSlugRoute,
} as any)
const EventHalfpriceTravelIndexRoute =
  EventHalfpriceTravelIndexRouteImport.update({
    id: '/event/halfprice-travel/',
    path: '/event/halfprice-travel/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WikiSlugReviewsRoute = WikiSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugMediaRoute = WikiSlugMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugBlogRoute = WikiSlugBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => WikiSlugRoute,
} as any)
const EventHalfpriceTravelSlugRoute =
  EventHalfpriceTravelSlugRouteImport.update({
    id: '/event/halfprice-travel/$slug',
    path: '/event/halfprice-travel/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test-designs': typeof TestDesignsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/web-sources': typeof AdminWebSourcesRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/all': typeof WikiAllRoute
  '/admin/': typeof AdminIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/halfprice-travel/$slug': typeof EventHalfpriceTravelSlugRoute
  '/wiki/$slug/blog': typeof WikiSlugBlogRoute
  '/wiki/$slug/media': typeof WikiSlugMediaRoute
  '/wiki/$slug/reviews': typeof WikiSlugReviewsRoute
  '/event/halfprice-travel/': typeof EventHalfpriceTravelIndexRoute
  '/wiki/$slug/': typeof WikiSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test-designs': typeof TestDesignsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/web-sources': typeof AdminWebSourcesRoute
  '/wiki/all': typeof WikiAllRoute
  '/admin': typeof AdminIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/halfprice-travel/$slug': typeof EventHalfpriceTravelSlugRoute
  '/wiki/$slug/blog': typeof WikiSlugBlogRoute
  '/wiki/$slug/media': typeof WikiSlugMediaRoute
  '/wiki/$slug/reviews': typeof WikiSlugReviewsRoute
  '/event/halfprice-travel': typeof EventHalfpriceTravelIndexRoute
  '/wiki/$slug': typeof WikiSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test-designs': typeof TestDesignsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/web-sources': typeof AdminWebSourcesRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/wiki/all': typeof WikiAllRoute
  '/admin/': typeof AdminIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/halfprice-travel/$slug': typeof EventHalfpriceTravelSlugRoute
  '/wiki/$slug/blog': typeof WikiSlugBlogRoute
  '/wiki/$slug/media': typeof WikiSlugMediaRoute
  '/wiki/$slug/reviews': typeof WikiSlugReviewsRoute
  '/event/halfprice-travel/': typeof EventHalfpriceTravelIndexRoute
  '/wiki/$slug/': typeof WikiSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/test-designs'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/tools'
    | '/admin/web-sources'
    | '/wiki/$slug'
    | '/wiki/all'
    | '/admin/'
    | '/wiki/'
    | '/api/auth/$'
    | '/event/halfprice-travel/$slug'
    | '/wiki/$slug/blog'
    | '/wiki/$slug/media'
    | '/wiki/$slug/reviews'
    | '/event/halfprice-travel/'
    | '/wiki/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/test-designs'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/tools'
    | '/admin/web-sources'
    | '/wiki/all'
    | '/admin'
    | '/wiki'
    | '/api/auth/$'
    | '/event/halfprice-travel/$slug'
    | '/wiki/$slug/blog'
    | '/wiki/$slug/media'
    | '/wiki/$slug/reviews'
    | '/event/halfprice-travel'
    | '/wiki/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/test-designs'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/tools'
    | '/admin/web-sources'
    | '/wiki/$slug'
    | '/wiki/all'
    | '/admin/'
    | '/wiki/'
    | '/api/auth/$'
    | '/event/halfprice-travel/$slug'
    | '/wiki/$slug/blog'
    | '/wiki/$slug/media'
    | '/wiki/$slug/reviews'
    | '/event/halfprice-travel/'
    | '/wiki/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestDesignsRoute: typeof TestDesignsRoute
  WikiSlugRoute: typeof WikiSlugRouteWithChildren
  WikiAllRoute: typeof WikiAllRoute
  WikiIndexRoute: typeof WikiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventHalfpriceTravelSlugRoute: typeof EventHalfpriceTravelSlugRoute
  EventHalfpriceTravelIndexRoute: typeof EventHalfpriceTravelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-designs': {
      id: '/test-designs'
      path: '/test-designs'
      fullPath: '/test-designs'
      preLoaderRoute: typeof TestDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wiki/all': {
      id: '/wiki/all'
      path: '/wiki/all'
      fullPath: '/wiki/all'
      preLoaderRoute: typeof WikiAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/web-sources': {
      id: '/admin/web-sources'
      path: '/web-sources'
      fullPath: '/admin/web-sources'
      preLoaderRoute: typeof AdminWebSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wiki/$slug/': {
      id: '/wiki/$slug/'
      path: '/'
      fullPath: '/wiki/$slug/'
      preLoaderRoute: typeof WikiSlugIndexRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/event/halfprice-travel/': {
      id: '/event/halfprice-travel/'
      path: '/event/halfprice-travel'
      fullPath: '/event/halfprice-travel/'
      preLoaderRoute: typeof EventHalfpriceTravelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/reviews': {
      id: '/wiki/$slug/reviews'
      path: '/reviews'
      fullPath: '/wiki/$slug/reviews'
      preLoaderRoute: typeof WikiSlugReviewsRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/media': {
      id: '/wiki/$slug/media'
      path: '/media'
      fullPath: '/wiki/$slug/media'
      preLoaderRoute: typeof WikiSlugMediaRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/blog': {
      id: '/wiki/$slug/blog'
      path: '/blog'
      fullPath: '/wiki/$slug/blog'
      preLoaderRoute: typeof WikiSlugBlogRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/event/halfprice-travel/$slug': {
      id: '/event/halfprice-travel/$slug'
      path: '/event/halfprice-travel/$slug'
      fullPath: '/event/halfprice-travel/$slug'
      preLoaderRoute: typeof EventHalfpriceTravelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminWebSourcesRoute: typeof AdminWebSourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminWebSourcesRoute: AdminWebSourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WikiSlugRouteChildren {
  WikiSlugBlogRoute: typeof WikiSlugBlogRoute
  WikiSlugMediaRoute: typeof WikiSlugMediaRoute
  WikiSlugReviewsRoute: typeof WikiSlugReviewsRoute
  WikiSlugIndexRoute: typeof WikiSlugIndexRoute
}

const WikiSlugRouteChildren: WikiSlugRouteChildren = {
  WikiSlugBlogRoute: WikiSlugBlogRoute,
  WikiSlugMediaRoute: WikiSlugMediaRoute,
  WikiSlugReviewsRoute: WikiSlugReviewsRoute,
  WikiSlugIndexRoute: WikiSlugIndexRoute,
}

const WikiSlugRouteWithChildren = WikiSlugRoute._addFileChildren(
  WikiSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestDesignsRoute: TestDesignsRoute,
  WikiSlugRoute: WikiSlugRouteWithChildren,
  WikiAllRoute: WikiAllRoute,
  WikiIndexRoute: WikiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventHalfpriceTravelSlugRoute: EventHalfpriceTravelSlugRoute,
  EventHalfpriceTravelIndexRoute: EventHalfpriceTravelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
