/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WikiSlugRouteImport } from './routes/wiki/$slug'
import { Route as AdminWebSourcesRouteImport } from './routes/admin/web-sources'
import { Route as AdminToolsRouteImport } from './routes/admin/tools'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as EventHalfpriceTravelIndexRouteImport } from './routes/event/halfprice-travel/index'
import { Route as WikiSlugReviewsRouteImport } from './routes/wiki/$slug.reviews'
import { Route as WikiSlugMediaRouteImport } from './routes/wiki/$slug.media'
import { Route as WikiSlugBlogRouteImport } from './routes/wiki/$slug.blog'
import { Route as EventHalfpriceTravelSlugRouteImport } from './routes/event/halfprice-travel/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebSourcesRoute = AdminWebSourcesRouteImport.update({
  id: '/web-sources',
  path: '/web-sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const EventHalfpriceTravelIndexRoute =
  EventHalfpriceTravelIndexRouteImport.update({
    id: '/event/halfprice-travel/',
    path: '/event/halfprice-travel/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WikiSlugReviewsRoute = WikiSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugMediaRoute = WikiSlugMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => WikiSlugRoute,
} as any)
const WikiSlugBlogRoute = WikiSlugBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => WikiSlugRoute,
} as any)
const EventHalfpriceTravelSlugRoute =
  EventHalfpriceTravelSlugRouteImport.update({
    id: '/event/halfprice-travel/$slug',
    path: '/event/halfprice-travel/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/web-sources': typeof AdminWebSourcesRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/halfprice-travel/$slug': typeof EventHalfpriceTravelSlugRoute
  '/wiki/$slug/blog': typeof WikiSlugBlogRoute
  '/wiki/$slug/media': typeof WikiSlugMediaRoute
  '/wiki/$slug/reviews': typeof WikiSlugReviewsRoute
  '/event/halfprice-travel/': typeof EventHalfpriceTravelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/web-sources': typeof AdminWebSourcesRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/halfprice-travel/$slug': typeof EventHalfpriceTravelSlugRoute
  '/wiki/$slug/blog': typeof WikiSlugBlogRoute
  '/wiki/$slug/media': typeof WikiSlugMediaRoute
  '/wiki/$slug/reviews': typeof WikiSlugReviewsRoute
  '/event/halfprice-travel': typeof EventHalfpriceTravelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/web-sources': typeof AdminWebSourcesRoute
  '/wiki/$slug': typeof WikiSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/event/halfprice-travel/$slug': typeof EventHalfpriceTravelSlugRoute
  '/wiki/$slug/blog': typeof WikiSlugBlogRoute
  '/wiki/$slug/media': typeof WikiSlugMediaRoute
  '/wiki/$slug/reviews': typeof WikiSlugReviewsRoute
  '/event/halfprice-travel/': typeof EventHalfpriceTravelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/tools'
    | '/admin/web-sources'
    | '/wiki/$slug'
    | '/admin/'
    | '/wiki/'
    | '/api/auth/$'
    | '/event/halfprice-travel/$slug'
    | '/wiki/$slug/blog'
    | '/wiki/$slug/media'
    | '/wiki/$slug/reviews'
    | '/event/halfprice-travel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/tools'
    | '/admin/web-sources'
    | '/wiki/$slug'
    | '/admin'
    | '/wiki'
    | '/api/auth/$'
    | '/event/halfprice-travel/$slug'
    | '/wiki/$slug/blog'
    | '/wiki/$slug/media'
    | '/wiki/$slug/reviews'
    | '/event/halfprice-travel'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/tools'
    | '/admin/web-sources'
    | '/wiki/$slug'
    | '/admin/'
    | '/wiki/'
    | '/api/auth/$'
    | '/event/halfprice-travel/$slug'
    | '/wiki/$slug/blog'
    | '/wiki/$slug/media'
    | '/wiki/$slug/reviews'
    | '/event/halfprice-travel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  WikiSlugRoute: typeof WikiSlugRouteWithChildren
  WikiIndexRoute: typeof WikiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventHalfpriceTravelSlugRoute: typeof EventHalfpriceTravelSlugRoute
  EventHalfpriceTravelIndexRoute: typeof EventHalfpriceTravelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/web-sources': {
      id: '/admin/web-sources'
      path: '/web-sources'
      fullPath: '/admin/web-sources'
      preLoaderRoute: typeof AdminWebSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/event/halfprice-travel/': {
      id: '/event/halfprice-travel/'
      path: '/event/halfprice-travel'
      fullPath: '/event/halfprice-travel/'
      preLoaderRoute: typeof EventHalfpriceTravelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/reviews': {
      id: '/wiki/$slug/reviews'
      path: '/reviews'
      fullPath: '/wiki/$slug/reviews'
      preLoaderRoute: typeof WikiSlugReviewsRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/media': {
      id: '/wiki/$slug/media'
      path: '/media'
      fullPath: '/wiki/$slug/media'
      preLoaderRoute: typeof WikiSlugMediaRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/wiki/$slug/blog': {
      id: '/wiki/$slug/blog'
      path: '/blog'
      fullPath: '/wiki/$slug/blog'
      preLoaderRoute: typeof WikiSlugBlogRouteImport
      parentRoute: typeof WikiSlugRoute
    }
    '/event/halfprice-travel/$slug': {
      id: '/event/halfprice-travel/$slug'
      path: '/event/halfprice-travel/$slug'
      fullPath: '/event/halfprice-travel/$slug'
      preLoaderRoute: typeof EventHalfpriceTravelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminWebSourcesRoute: typeof AdminWebSourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminWebSourcesRoute: AdminWebSourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WikiSlugRouteChildren {
  WikiSlugBlogRoute: typeof WikiSlugBlogRoute
  WikiSlugMediaRoute: typeof WikiSlugMediaRoute
  WikiSlugReviewsRoute: typeof WikiSlugReviewsRoute
}

const WikiSlugRouteChildren: WikiSlugRouteChildren = {
  WikiSlugBlogRoute: WikiSlugBlogRoute,
  WikiSlugMediaRoute: WikiSlugMediaRoute,
  WikiSlugReviewsRoute: WikiSlugReviewsRoute,
}

const WikiSlugRouteWithChildren = WikiSlugRoute._addFileChildren(
  WikiSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  WikiSlugRoute: WikiSlugRouteWithChildren,
  WikiIndexRoute: WikiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventHalfpriceTravelSlugRoute: EventHalfpriceTravelSlugRoute,
  EventHalfpriceTravelIndexRoute: EventHalfpriceTravelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
